services:
  - type: web
    name: oceanai-backend
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn backend.app.main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: DATABASE_URL
        fromDatabase:
          name: oceanai-db
          property: connectionString
      - key: CORS_ORIGINS
        value: https://your-frontend.netlify.app,http://localhost:5173
  
  - type: pserv
    name: oceanai-db
    env: postgresql
    plan: free
    databaseName: oceandb
    databaseUser: oceanuser